Download student work cli
freeuni-digital-technologies/classroom-api pull request #2
Opened 2020-10-22 20:13 UTC by khokho

Readme ში წერია აღწერა გამოყენების ;დ

2020-10-26 08:05 UTC, iarigby commented
მშვენიერია.

ახლა ისღა დარჩა გლობალური command იყოს. 

## იუზერისთვის
1. npm-ზე დამატება
2. github action მიბმა, რომ მასტერის შეცვლისას ავტომატურად დაგენერირდეს ახალი (ამ დროს მგონი ვერსიაც უნდა შევცვალოთ ხოლმე, ამიტომ dev ბრენჩი შევქმნათ)

## დეველოპმენტისას კონკრეტული ბრენჩის დატესტვა
npm install username/repo#branchName --save

P.S ამ შემთხვევაში credentials.json და token.jsonს გლობალური path ჭირდება. თუ გამოძახების დირექტორიაში არ არის, ~/.config/classroom-api -ში მოძებნოს (იუზერს აცნობოს)

2020-10-26 08:27 UTC, iarigby requested changes
.

2020-10-26 15:08 UTC, iarigby commented
დედლაინის გადაცილების flag-იც დასამატებელია (ყველა გადმოწეროს ან რომელიც on time არის)

2020-10-26 15:14 UTC, iarigby commented
ახლა ვცადე ზიპის გახსნა და არ მუშაობს. ზიპის გადმოწერისას რაღაც სხვა უნდოდა, module-js-ის მთავარ ფაილში შეიძლება იყოს მაგისთვის თუ რამე კოდია საჭირო.

2020-11-05 10:41 UTC, khokho commented
ცალკე ზიპისთვის კოდის წერა და ცალკე ფაილების არ მგონია ლამაზი ამიტომ ამის მიხედვით გადავაკეთე გადმოწერები:

https://github.com/googleapis/google-api-nodejs-client/blob/master/samples/drive/download.js

flag-ებს დავამატებ დედლაინისას და კიდე ზიპებს ექსტრაქტი რო გაუკეთოს მაგას.

2020-11-05 10:59 UTC, khokho commented
ძველი კლასრუმის ვების დავალების ზიპებს იწერს კარგად.

2020-11-05 17:09 UTC, khokho commented
autoextract დავუმატე მარა ჯერჯერობით იმას არ ვაკვირდები ზიპის გახსნის მერე ფაილები პირდაპირ არის თუ ფოლდერშია. ამას ზუსტად რა ვუყო ერთად მოვიფიქროთ და დავამატებ მერე. აქამდე როგორც გავიგე index.html ს პოულობდი და მაგის შემცველ ფოლდერს აბრუნებდი dir-ად.

2020-11-29 11:17 UTC, iarigby requested changes
დავტესტე პარადიგმების დავალებაზე და მუშაობს! მაგარია

შენიშვნები:
- თითო დავალებაზე იყოს ნებისმიერი ერორის დაჭერა, ისე რომ თუ რამე ახალი შეცდომა მოხდა მაინც გააგრძელოს დანარჩენების გადმოწერა.
- მოცემული დირექტორია თუ არ არსებობს, არ ჯობია შექმნას? ან უბრალოდ დაიჭიროს მაინც ეგ შეცდომა და იუზერს მესიჯად მიუვიდეს და არა დიდ json ერორად
- თუ უკვე გადმოწერილია რას გააკეთებს? მაგისთვისაც ხომ არ სჯობს flag. უკვე გადმოწერილზე არ შეამოწმოს ოღონდ ფაილი არსებობს თუ არა. დიდი დრო დაიზოგება. 
- მეილის აიდების სიით რომ მიუთითო ვინების გადმოწეროს
- დაინსტალირებად პროგრამაზე რა ხდება? yarn-ის გარეშე რომ გამოიძახოს ნებისმიერი ადგილიდან და აფდეითზე git pull, yarn install, yarn build სათითაოდ რომ არ იყოს საჭირო იუზერისთვის. ისე ამ შემთხვევაში relative path-ით შეძლოს მითითება - download -p ./zips

2020-12-28 17:05 UTC, khokho commented
> მოცემული დირექტორია თუ არ არსებობს, არ ჯობია შექმნას? ან უბრალოდ დაიჭიროს მაინც ეგ შეცდომა და იუზერს მესიჯად მიუვიდეს და არა დიდ json ერორად

მარტივ ერორს ვაწერინებ ახლა. შეცდომის გამო მერე ფოლდერების შლა არ მინდა რომ მოუწიოს იუზერს. თურამეა გადავაკეთებ არაა პრობლემა. 
> მეილის აიდების სიით რომ მიუთითო ვინების გადმოწეროს 

რა სახით მივცე? 
download ...args... alkhok18 glekv20 ... ასე დავუშვათ? 
და ეს მეილები students.json-ში უნდა მხვდებოდეს?

2020-12-28 18:36 UTC, iarigby commented
სჯობს შეცდომის შემთხვევაში წაშალოს ვიდრე გამოყენებისას ყოველ ჯერზე თავისით
მოუწიოს შექმნა. ხშირად შემხვედრია დირექტორიის შექმნა დიფაულტად და არ არის
პრობლემა.

students.json კიდევ არის? :D კი მგონი ლოგიკურია. კონსოლში დაწერე უბრალოდ თუ
ვერ მოიძებნა. cli ბიბლიოთეკას აქვს students=user1,user2 და ავტომატურად სიად
გარდაქმნის.





On Mon, Dec 28, 2020 at 9:05 PM Aleksandre Khokhiashvili <
notifications@github.com> wrote:

> მოცემული დირექტორია თუ არ არსებობს, არ ჯობია შექმნას? ან უბრალოდ დაიჭიროს
> მაინც ეგ შეცდომა და იუზერს მესიჯად მიუვიდეს და არა დიდ json ერორად
>
> მარტივ ერორს ვაწერინებ ახლა. შეცდომის გამო მერე ფოლდერების შლა არ მინდა
> რომ მოუწიოს იუზერს. თურამეა გადავაკეთებ არაა პრობლემა.
>
> მეილის აიდების სიით რომ მიუთითო ვინების გადმოწეროს
>
> რა სახით მივცე?
> download ...args... alkhok18 glekv20 ... ასე დავუშვათ?
> და ეს მეილები students.json-ში უნდა მხვდებოდეს?
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/freeuni-digital-technologies/classroom-api/pull/2#issuecomment-751789342>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AC6OOQYHI4SYDXFHLDUDIUTSXC3FZANCNFSM4S3VS5PQ>
> .
>

2020-12-28 18:43 UTC, khokho commented
რეკურსიულად ყველა შევაქმნევინო თუ მარტო ერთი? ;დ

2020-12-29 08:28 UTC, khokho commented
დაინსტალირებად პროგრამად გადაკეთება დამრჩა მარა ანუ ზუსტად ვერ ვხვდები რა უნდა ვქნა. ცალკე ეს download სკრიპტი უნდა იყოს დაყენებადი ხო? და როგორ რო მითხრა დაახლოებთ.

2020-12-29 10:42 UTC, iarigby commented
კი. მეგონა ადრე დავლინკე მაგრამ ვეღარ ვპოულობ

2021-09-20 20:22 UTC, khokho commented
ამას დავმერჯავ იმიტორო სხვა მოდულები დამოკიდებულია ამ ბრენჩზე უკვე და master-ზე რომ იყოს ამარტივებს ბევრს რამეს. :smile:
დაინსტალირებად პროგრამად გადაკეთების ცალკე issue გავხსენი #7

2021-09-20 20:24 UTC, merged